# Generated by Django 5.2.8 on 2025-11-26 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('origen', models.CharField(choices=[('reserva', 'Desde reserva'), ('detalle', 'Desde detalle')], default='detalle', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.clientes')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.libros')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.reservas')),
            ],
            options={
                'db_table': 'solicitudes_venta',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(blank=True, default='pagada', max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.clientes')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.usuarios')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='biblio.libros')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='biblio.ventas')),
            ],
            options={
                'db_table': 'detalle_ventas',
            },
        ),
    ]
