# Generated by Django 5.2.8 on 2025-11-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_solicitudventa_ventas_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='impuesto_porcentaje',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje de impuesto aplicado a este libro.', max_digits=5),
        ),
        migrations.AddField(
            model_name='libros',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de venta al público (Lempiras).', max_digits=10),
        ),
    ]
