# Generated by Django 5.2.8 on 2025-11-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_libros_impuesto_porcentaje_libros_precio_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('rtn', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('suministro', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='primer_ingreso',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='compras_registradas', to='biblio.usuarios')),
                ('proveedor', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='biblio.proveedores')),
            ],
            options={
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(db_column='compra_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='biblio.compras')),
                ('libro', models.ForeignKey(db_column='libro_id', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='biblio.libros')),
            ],
            options={
                'db_table': 'detalle_compras',
            },
        ),
    ]
